{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-service-monitor
  labels:
    release: prometheus {{/* Only services which have this matching label will be monitored by the ServiceMonitor */}}
spec:
  endpoints:
    - port: metrics
      path: {{ .Values.serviceMonitor.path }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      up42.com/app: {{ .Release.Name }}
{{- end }}

